spring.application.name=documentTestITQ

# Database
spring.datasource.url=jdbc:postgresql://localhost:5432/documentdb
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA/Hibernate
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.?dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.open-in-view=false

# Liquibase
spring.liquibase.change-log=classpath:db/changelog/db.changelog-master.xml
spring.liquibase.enabled=true

# Workers
workers.submit.enabled=false
workers.submit.interval=5000
workers.submit.batchSize=100
workers.approve.enabled=false
workers.approve.interval=5000
workers.approve.batchSize=100


logging.level.com.globsest.documenttestitq=INFO
logging.level.org.springframework.web=INFO
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE
logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss} - %msg%n


server.port=8080
